version: '3.8'

services:
  rsa_frontend:
    build:
      context: ../rsa_app-rsa_newUI
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://rsa_api:5000/
    container_name: rsa_frontend
    ports:
      - "3000:3000"
    depends_on:
      - rsa_api
    restart: unless-stopped

  rsa_api:
    build: .
    container_name: rsa_api
    ports:
      - "5000:5000"
    environment:
      APP_URL: http://localhost:3000/   # Used in email links
      DB_HOST: db
      DB_NAME: rsa
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: rsa_db
    environment:
      POSTGRES_DB: rsa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
